### ISSUE TITLE
T04 Lab - Function App package restore authorization error

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#49]
## Location

- Course: az-203T04
- Exercise: 04
- Task: 03
- Step[s]: 6

## Description

Fails to restore packages for the function app

## Repro steps

While testing the function app, package restore in the function app console gives authorization errors:

2019-07-17T15:24:00.647 [Information] Restoring packages.
2019-07-17T15:24:00.674 [Information] Starting packages restore
2019-07-17T15:24:01.372 [Information] System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
2019-07-17T15:24:01.373 [Information] at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
2019-07-17T15:24:01.392 [Information] at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
2019-07-17T15:24:01.392 [Information] at System.Environment.SetEnvironmentVariableCore(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T15:24:01.392 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T15:24:01.393 [Information] at Internal.Runtime.Augments.EnvironmentAugments.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T15:24:01.397 [Information] at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T15:24:01.397 [Information] at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
2019-07-17T15:24:01.398 [Information] at Microsoft.DotNet.ShellShim.WindowsEnvironmentPath.AddPackageExecutablePathToUserPath()
2019-07-17T15:24:01.398 [Information] at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
2019-07-17T15:24:01.398 [Information] at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
2019-07-17T15:24:01.399 [Information] at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2019-07-17T15:24:01.399 [Information] at Microsoft.DotNet.Cli.Program.Main(String[] args)
2019-07-17T15:24:01.415 [Information] Packages restored.
2019-07-17T15:24:01.528 [Warning] You may be referencing NuGet packages incorrectly. Learn more: https://go.microsoft.com/fwlink/?linkid=2091419
2019-07-17T15:24:01.529 [Warning] You may be referencing NuGet packages incorrectly. Learn more: https://go.microsoft.com/fwlink/?linkid=2091419
2019-07-17T15:24:01.530 [Warning] You may be referencing NuGet packages incorrectly. Learn more: https://go.microsoft.com/fwlink/?linkid=2091419
2019-07-17T15:24:01.531 [Warning] You may be referencing NuGet packages incorrectly. Learn more: https://go.microsoft.com/fwlink/?linkid=2091419
2019-07-17T15:24:01.610 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2019-07-17T15:24:01.671 [Error] run.csx(3,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
2019-07-17T15:24:01.757 [Error] run.csx(4,17): error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
2019-07-17T15:24:01.837 [Error] run.csx(9,5): error CS0246: The type or namespace name 'CloudStorageAccount' could not be found (are you missing a using directive or an assembly reference?)
2019-07-17T15:24:01.924 [Error] Executed 'Functions.FileParser' (Failed, Id=2a8bcded-fdd4-4e90-87cc-7f085dc5c5b1)
The process cannot access the file 'D:\home\LogFiles\Application\Functions\Function\FileParser\2019-07-17T15-03-54Z-c2e298dcd6.log' because it is being used by another process.

**Comment by seesharprun** [comment]
Thanks for the second report. I have a question out to the Functions team about this.

**Comment by romilbheda** [comment]
Add Microsoft Azure Storage Reference in run.csx file
**#r "Microsoft.WindowsAzure.Storage"**

Ex.
#r "Microsoft.WindowsAzure.Storage"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

public static async Task<IActionResult> Run(HttpRequest req)
{
   ........
}

**Comment by seesharprun** [comment]
I'm still trying to validate that this is the correct solution for the lab.

**Comment by seesharprun** [comment]
In Issue #17, it has been confimed that setting ``DOTNET_SKIP_FIRST_TIME_EXPERIENCE`` to ``true`` in the application settings resolves this bug. I will add the fix to the lab this week.

**Comment by seesharprun** [comment]
This bug was resolved in [Version 20190725.03](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190725.03).
