### ISSUE TITLE
Lab03 - RedisConnectionException: No connection is available to service this operation: GET az:dev:student; UnableToConnect

### ISSUE THREAD

**Issue by kashif-khan** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#97]
## Location

- Course: AZ-203
- Exercise: 06
- Task: 05
- Step: 07

## Description

`_database.StringGetAsync(uniqueIdentifier)` throws error "No connection is available to service this operation"

Description of issue

Unable to retrieve RedisCache value.

## Repro steps

1. Select any product by clicking `view details`
2. Select a model and click `add to cart`

## Exception

```
info: Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker[4]
      Executed page /Cart in 17619.6146ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Page: /Cart'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET az:dev:student; UnableToConnect on polyrediscachexxxxx1120.redis.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402; IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on polyrediscachexxxxx1120.redis.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive:
60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2201
--- End of stack trace from previous location where exception was thrown ---
   at AdventureWorks.Context.AdventureWorksRedisContext.AddProductToCartAsync(String uniqueIdentifier, Product product) in C:\github\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Starter\AdventureWorks\AdventureWorks.Context\AdventureWorksRedisContext.cs:line 22
   at AdventureWorks.Web.Pages.Cart.OnGetAsync(Nullable`1 add) in C:\github\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Starter\AdventureWorks\AdventureWorks.Web\Pages\Cart.cshtml.cs:line 36
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by seesharprun** [comment]
This error occurs if the value of the ``ConnectionStrings.AdventureWorksRedisContext`` setting in the **appsettings.json** file is incorrect. This is the first time that the code connects to the Redis database.
